name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: your-dockerhub-username/my-python-app:latest

      - name: Helm package
        run: helm package my-python-app

      - name: Helm push
        uses: helm/chart-releaser-action@v2
        with:
          chart-repo: your-helm-repo
          charts: my-python-app-*.tgz

      - name: Deploy to Kubernetes
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2
        run: |
          helm upgrade --install my-python-app ./my-python-app --namespace default

