name: Deploy to Docker Hub, GitHub Pages & Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-k8s-helm:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/python-k8s-helm:latest

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Package Helm chart into TGZ
        run: |
          mkdir -p charts
          helm package MY-PYTHON-APP --destination charts

      - name: Prepare GitHub Pages directory
        run: |
          mkdir -p public
          cp charts/*.tgz public/
          helm repo index public --url https://zolbergeli.github.io/kubernetes-deployment/ --merge public/index.yaml

      - name: Create index.html for GitHub Pages
        run: |
          echo "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Helm Charts Repository</title></head><body><h1>Helm Charts Repository</h1><p>This is the Helm charts repository.</p><ul>$(for file in public/*.tgz; do echo "<li><a href=\"$(basename $file)\">$(basename $file)</a></li>"; done)</ul></body></html>" > public/index.html

      - name: Upload Helm charts to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public

      - name: Deploy with Helm
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          helm upgrade --install my-python-app ./path/to/your/helm/chart
